#!/usr/bin/env python3
"""
bulk_tetra_template_mapper.py

Stage-2 bulk tetrahedral-site mapper for BCC Fe bicrystal/polycrystal KMC.

Purpose
-------
Consumes the region masks generated by gb_bulk_region_classifier.py and creates
bulk-region tetrahedral interstitial sites using a local orientation-aware BCC
template. It does NOT generate GB/core sites; those are left for the later
Voronoi/Delaunay stage.

Method
------
For each BULK_TEMPLATE Fe atom:
  1. Find its nearest Fe neighbors.
  2. Fit a local BCC orientation from the 8 first-neighbor body-diagonal vectors.
  3. Place the analytical BCC tetrahedral-site template around that atom.
  4. Keep candidates that are sufficiently far from Fe atoms and not inside the
     GB_VORONOI region.
  5. Merge duplicate candidate sites produced by neighboring Fe atoms.

The output is a deterministic bulk-template site map suitable for combining
later with GB Voronoi/Delaunay sites into a KMC site graph.

Dependencies: numpy only.

Example
-------
python3 bulk_tetra_template_mapper.py sigma5_210-20-20-5.lmp \
    --masks sigma5_regions_masks.npz \
    --a0 2.856 \
    --out-prefix sigma5_bulk_tetra

Outputs
-------
<out-prefix>_sites.csv
<out-prefix>_sites.xyz
<out-prefix>_summary.txt
<out-prefix>_sites.npz
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np

from lammps_data_utils import read_lammps_atomic_data


def wrap_positions(pos: np.ndarray, box: np.ndarray) -> np.ndarray:
    lo = box[:, 0]
    L = box[:, 1] - box[:, 0]
    return lo + np.mod(pos - lo, L)


def minimum_image(delta: np.ndarray, L: np.ndarray) -> np.ndarray:
    return delta - L * np.round(delta / L)


class PeriodicCellList:
    def __init__(self, positions: np.ndarray, box: np.ndarray, cutoff: float):
        self.pos = wrap_positions(np.asarray(positions, dtype=float), box)
        self.box = box
        self.lo = box[:, 0]
        self.L = box[:, 1] - box[:, 0]
        self.cutoff = float(cutoff)
        self.cutoff2 = self.cutoff * self.cutoff
        self.ncell = np.maximum(np.floor(self.L / self.cutoff).astype(int), 1)
        self.cell_size = self.L / self.ncell
        self.cells: Dict[Tuple[int, int, int], List[int]] = {}
        frac = (self.pos - self.lo) / self.cell_size
        self.atom_cells = np.floor(frac).astype(int) % self.ncell
        for i, c in enumerate(self.atom_cells):
            self.cells.setdefault(tuple(int(x) for x in c), []).append(i)
        ranges = [range(-1 if n > 1 else 0, 2 if n > 1 else 1) for n in self.ncell]
        self.offsets = [(i, j, k) for i in ranges[0] for j in ranges[1] for k in ranges[2]]

    def query_point(self, p: np.ndarray, cutoff: float | None = None) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        if cutoff is None:
            cutoff = self.cutoff
        cutoff2 = cutoff * cutoff
        p = wrap_positions(np.asarray(p, dtype=float).reshape(1, 3), self.box)[0]
        ci = np.floor((p - self.lo) / self.cell_size).astype(int) % self.ncell
        ids: List[int] = []
        vecs: List[np.ndarray] = []
        dists: List[float] = []
        seen = set()
        for off in self.offsets:
            ck = tuple(((ci + np.array(off, dtype=int)) % self.ncell).tolist())
            for j in self.cells.get(ck, []):
                if j in seen:
                    continue
                seen.add(j)
                dv = minimum_image(self.pos[j] - p, self.L)
                d2 = float(np.dot(dv, dv))
                if d2 <= cutoff2:
                    ids.append(j)
                    vecs.append(dv)
                    dists.append(math.sqrt(d2))
        if not ids:
            return np.empty(0, dtype=int), np.empty((0, 3), dtype=float), np.empty(0, dtype=float)
        order = np.argsort(dists)
        return np.array(ids, dtype=int)[order], np.array(vecs, dtype=float)[order], np.array(dists, dtype=float)[order]

    def query_index(self, idx: int, cutoff: float | None = None) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        ids, vecs, dists = self.query_point(self.pos[idx], cutoff)
        keep = ids != idx
        return ids[keep], vecs[keep], dists[keep]


def bcc_tetra_fractional_offsets() -> np.ndarray:
    """12 tetrahedral positions of BCC in conventional-cell fractional coords."""
    vals = []
    # One coordinate on a cell face (0), one coordinate at 1/2, one at 1/4 or 3/4.
    for face_axis in range(3):
        other = [a for a in range(3) if a != face_axis]
        for half_axis, quarter_axis in [(other[0], other[1]), (other[1], other[0])]:
            for q in (0.25, 0.75):
                f = np.zeros(3, dtype=float)
                f[face_axis] = 0.0
                f[half_axis] = 0.5
                f[quarter_axis] = q
                vals.append(f)
    return np.array(vals, dtype=float)


IDEAL_DIAGONALS = np.array(
    [[sx, sy, sz] for sx in (-1, 1) for sy in (-1, 1) for sz in (-1, 1)], dtype=float
) / math.sqrt(3.0)
TETRA_FRAC = bcc_tetra_fractional_offsets()


def kabsch_rotation(A: np.ndarray, B: np.ndarray) -> np.ndarray:
    """Return R that best maps A rows onto B rows: A @ R.T ~= B."""
    H = A.T @ B
    U, _, Vt = np.linalg.svd(H)
    R = Vt.T @ U.T
    if np.linalg.det(R) < 0:
        Vt[-1, :] *= -1
        R = Vt.T @ U.T
    return R


def fit_local_bcc_frame(neighbor_vecs: np.ndarray, a0: float) -> Tuple[np.ndarray | None, float]:
    """Fit local conventional BCC axes from 8 first-neighbor body-diagonal vectors.

    Returns (basis, rms_angular_error), where basis columns are the local a,b,c
    conventional-cell axis vectors in Cartesian coordinates.
    """
    if len(neighbor_vecs) < 8:
        return None, float("inf")
    V = neighbor_vecs[:8].copy()
    norms = np.linalg.norm(V, axis=1)
    good = norms > 1e-8
    if np.sum(good) < 8:
        return None, float("inf")
    Uvec = V[good][:8] / norms[good][:8, None]

    # Assign each observed body diagonal to the closest unused ideal diagonal.
    dots = Uvec @ IDEAL_DIAGONALS.T
    pairs = []
    used_obs = set()
    used_ideal = set()
    for _ in range(8):
        best = None
        best_val = -2.0
        for i in range(8):
            if i in used_obs:
                continue
            for j in range(8):
                if j in used_ideal:
                    continue
                val = dots[i, j]
                if val > best_val:
                    best_val = val
                    best = (i, j)
        if best is None:
            break
        i, j = best
        used_obs.add(i)
        used_ideal.add(j)
        pairs.append((i, j))
    if len(pairs) < 8:
        return None, float("inf")

    A = np.array([IDEAL_DIAGONALS[j] for _, j in pairs])
    B = np.array([Uvec[i] for i, _ in pairs])
    R = kabsch_rotation(A, B)
    pred = A @ R.T
    err = float(np.sqrt(np.mean(np.sum((pred - B) ** 2, axis=1))))
    basis = R * a0  # columns are rotated conventional axes of length a0
    return basis, err


def merge_points_periodic(points: np.ndarray, box: np.ndarray, radius: float) -> Tuple[np.ndarray, np.ndarray]:
    """Greedy periodic merge. Returns merged points and counts."""
    if len(points) == 0:
        return points.reshape(0, 3), np.empty(0, dtype=int)
    points = wrap_positions(points, box)
    cl = PeriodicCellList(points, box, radius)
    L = box[:, 1] - box[:, 0]
    visited = np.zeros(len(points), dtype=bool)
    merged = []
    counts = []
    for i in range(len(points)):
        if visited[i]:
            continue
        ids, vecs, _ = cl.query_point(points[i], radius)
        ids = ids[~visited[ids]]
        if len(ids) == 0:
            continue
        # Average in unwrapped coordinates relative to point i.
        rel = []
        for j in ids:
            rel.append(minimum_image(points[j] - points[i], L))
        center = points[i] + np.mean(np.array(rel), axis=0)
        merged.append(wrap_positions(center.reshape(1, 3), box)[0])
        counts.append(len(ids))
        visited[ids] = True
    return np.array(merged), np.array(counts, dtype=int)


def write_xyz(path: str, sites: np.ndarray, box: np.ndarray) -> None:
    """Write OVITO-friendly extended XYZ preserving the simulation cell."""
    lo = box[:, 0]
    L = box[:, 1] - box[:, 0]
    sites = wrap_positions(np.asarray(sites, dtype=float), box)
    with open(path, "w") as f:
        f.write(f"{len(sites)}\n")
        f.write(
            'Lattice="'
            f'{L[0]:.10f} 0.0 0.0 0.0 {L[1]:.10f} 0.0 0.0 0.0 {L[2]:.10f}'
            '" '
            f'Origin="{lo[0]:.10f} {lo[1]:.10f} {lo[2]:.10f}" '
            'Properties=species:S:1:pos:R:3 '
            'pbc="T T T" '
            'Comment="bulk-template tetrahedral sites from BCC Fe local orientation mapping"\n'
        )
        for p in sites:
            f.write(f"H {p[0]:.8f} {p[1]:.8f} {p[2]:.8f}\n")


def write_lammps_sites(path: str, sites: np.ndarray, box: np.ndarray, atom_type: int = 1) -> None:
    """Write a minimal LAMMPS atomic data file containing only tetra sites."""
    sites = wrap_positions(np.asarray(sites, dtype=float), box)
    with open(path, "w") as f:
        f.write("LAMMPS data file: bulk tetrahedral interstitial sites only\n\n")
        f.write(f"{len(sites)} atoms\n")
        f.write("1 atom types\n\n")
        f.write(f"{box[0,0]:.10f} {box[0,1]:.10f} xlo xhi\n")
        f.write(f"{box[1,0]:.10f} {box[1,1]:.10f} ylo yhi\n")
        f.write(f"{box[2,0]:.10f} {box[2,1]:.10f} zlo zhi\n\n")
        f.write("Atoms # atomic\n\n")
        for i, p in enumerate(sites, start=1):
            f.write(f"{i} {atom_type} {p[0]:.10f} {p[1]:.10f} {p[2]:.10f}\n")


def write_csv(
    path: str,
    sites: np.ndarray,
    nearest_fe_dist: np.ndarray,
    nearest_gb_dist: np.ndarray,
    multiplicity: np.ndarray,
    grain_id: np.ndarray,
) -> None:
    with open(path, "w") as f:
        f.write("site_id,x,y,z,site_type,grain_id,nearest_fe_dist,nearest_gb_voronoi_fe_dist,multiplicity\n")
        for i, p in enumerate(sites):
            f.write(
                f"{i},{p[0]:.10f},{p[1]:.10f},{p[2]:.10f},BULK_TETRA,{int(grain_id[i])},"
                f"{nearest_fe_dist[i]:.8f},{nearest_gb_dist[i]:.8f},{int(multiplicity[i])}\n"
            )


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate bulk-region BCC tetrahedral sites from region masks.")
    ap.add_argument("data_file", help="LAMMPS data file")
    ap.add_argument("--masks", required=True, help="NPZ masks file from gb_bulk_region_classifier.py")
    ap.add_argument("--fe-type", type=int, default=1)
    ap.add_argument("--a0", type=float, default=2.856)
    ap.add_argument("--neighbor-cut", type=float, default=None, help="Cutoff to collect BCC first neighbors; default midpoint of 1st/2nd shell")
    ap.add_argument("--max-frame-error", type=float, default=0.20, help="Reject local BCC frame if unit-vector RMS fit error exceeds this")
    ap.add_argument("--min-fe-dist", type=float, default=1.05, help="Reject tetra site if closer than this to any Fe")
    ap.add_argument("--max-fe-dist", type=float, default=2.20, help="Reject tetra site if nearest Fe is farther than this")
    ap.add_argument("--gb-exclusion", type=float, default=3.0, help="Reject site if within this distance of any GB_VORONOI Fe atom")
    ap.add_argument("--merge-radius", type=float, default=0.22)
    ap.add_argument("--sample-stride", type=int, default=1, help="Use every Nth BULK_TEMPLATE Fe atom for debugging; default 1")
    ap.add_argument("--out-prefix", default="bulk_tetra")
    args = ap.parse_args()

    data = read_lammps_atomic_data(args.data_file)
    data.pos = wrap_positions(data.pos, data.box)
    masks = np.load(args.masks, allow_pickle=True)

    fe_global = masks["fe_indices_global"].astype(int)
    fe_pos = data.pos[fe_global]
    bulk_mask = masks["fe_bulk_template"].astype(bool)
    gb_mask = masks["fe_gb_voronoi"].astype(bool)
    fe_grain_id = masks["fe_grain_id"].astype(int) if "fe_grain_id" in masks else -np.ones(len(fe_pos), dtype=int)
    bulk_indices = np.where(bulk_mask)[0]
    gb_indices = np.where(gb_mask)[0]

    if args.sample_stride > 1:
        bulk_indices = bulk_indices[:: args.sample_stride]

    r1 = math.sqrt(3.0) * args.a0 / 2.0
    r2 = args.a0
    neighbor_cut = args.neighbor_cut if args.neighbor_cut is not None else 0.5 * (r1 + r2)

    print(f"Read {len(data.pos)} atoms; Fe atoms: {len(fe_pos)}")
    print(f"BULK_TEMPLATE Fe atoms used: {len(bulk_indices)}")
    print(f"GB_VORONOI Fe atoms: {len(gb_indices)}")
    print(f"Using neighbor_cut={neighbor_cut:.4f} Å, a0={args.a0:.4f} Å")

    fe_cl = PeriodicCellList(fe_pos, data.box, max(neighbor_cut, args.max_fe_dist, args.gb_exclusion, args.merge_radius))
    gb_cl = PeriodicCellList(fe_pos[gb_indices], data.box, args.gb_exclusion) if len(gb_indices) else None

    raw_sites: List[np.ndarray] = []
    frame_errors: List[float] = []
    accepted_frames = 0
    rejected_frames = 0

    for n_done, fe_i in enumerate(bulk_indices, 1):
        ids, vecs, dists = fe_cl.query_index(fe_i, neighbor_cut)
        first_vecs = vecs[:8]
        basis, err = fit_local_bcc_frame(first_vecs, args.a0)
        if basis is None or err > args.max_frame_error:
            rejected_frames += 1
            continue
        accepted_frames += 1
        frame_errors.append(err)
        origin = fe_pos[fe_i]
        # Tetra position = origin + basis @ fractional_offset.
        cand = origin + TETRA_FRAC @ basis.T
        raw_sites.extend(cand)
        if n_done % 5000 == 0:
            print(f"  processed {n_done}/{len(bulk_indices)} bulk atoms; raw candidates={len(raw_sites)}")

    raw_sites_arr = wrap_positions(np.array(raw_sites, dtype=float).reshape(-1, 3), data.box)
    print(f"Raw candidate tetra sites: {len(raw_sites_arr)}")
    print(f"Accepted local BCC frames: {accepted_frames}; rejected: {rejected_frames}")

    if len(raw_sites_arr) == 0:
        raise RuntimeError("No raw tetrahedral candidates generated. Check masks/cutoffs.")

    merged_sites, multiplicity = merge_points_periodic(raw_sites_arr, data.box, args.merge_radius)
    print(f"Merged candidate tetra sites: {len(merged_sites)}")

    # Filter by nearest Fe distance and GB exclusion distance.
    keep = np.ones(len(merged_sites), dtype=bool)
    nearest_fe_dist = np.full(len(merged_sites), np.inf)
    nearest_fe_idx = np.full(len(merged_sites), -1, dtype=int)
    nearest_gb_dist = np.full(len(merged_sites), np.inf)

    for i, p in enumerate(merged_sites):
        ids, _, d = fe_cl.query_point(p, args.max_fe_dist)
        if len(d) == 0:
            keep[i] = False
            continue
        nearest_fe_idx[i] = int(ids[0])
        nearest_fe_dist[i] = float(d[0])
        if nearest_fe_dist[i] < args.min_fe_dist or nearest_fe_dist[i] > args.max_fe_dist:
            keep[i] = False
            continue
        if gb_cl is not None and args.gb_exclusion > 0:
            _, _, dg = gb_cl.query_point(p, args.gb_exclusion)
            if len(dg) > 0:
                nearest_gb_dist[i] = float(dg[0])
                keep[i] = False

    final_sites = merged_sites[keep]
    final_fe_dist = nearest_fe_dist[keep]
    final_gb_dist = nearest_gb_dist[keep]
    final_mult = multiplicity[keep]
    final_nearest_fe_idx = nearest_fe_idx[keep]
    final_grain_id = np.full(len(final_sites), -1, dtype=int)
    valid_nearest = (final_nearest_fe_idx >= 0) & (final_nearest_fe_idx < len(fe_grain_id))
    final_grain_id[valid_nearest] = fe_grain_id[final_nearest_fe_idx[valid_nearest]]

    prefix = args.out_prefix
    write_csv(f"{prefix}_sites.csv", final_sites, final_fe_dist, final_gb_dist, final_mult, final_grain_id)
    write_xyz(f"{prefix}_sites.xyz", final_sites, data.box)
    write_lammps_sites(f"{prefix}_sites.lmp", final_sites, data.box)
    np.savez(
        f"{prefix}_sites.npz",
        positions=final_sites,
        nearest_fe_dist=final_fe_dist,
        nearest_gb_voronoi_fe_dist=final_gb_dist,
        multiplicity=final_mult,
        grain_id=final_grain_id,
        nearest_fe_local_index=final_nearest_fe_idx,
        box=data.box,
        a0=args.a0,
        site_type=np.array(["BULK_TETRA"] * len(final_sites)),
    )

    frame_err = np.array(frame_errors, dtype=float)
    summary = f"""
Input: {args.data_file}
Masks: {args.masks}
Fe atoms: {len(fe_pos)}
BULK_TEMPLATE Fe atoms used: {len(bulk_indices)}
GB_VORONOI Fe atoms: {len(gb_indices)}

a0 = {args.a0:.6f} Å
neighbor_cut = {neighbor_cut:.6f} Å
max_frame_error = {args.max_frame_error:.6f}
min_fe_dist = {args.min_fe_dist:.6f} Å
max_fe_dist = {args.max_fe_dist:.6f} Å
gb_exclusion = {args.gb_exclusion:.6f} Å
merge_radius = {args.merge_radius:.6f} Å

Accepted local BCC frames: {accepted_frames}
Rejected local BCC frames: {rejected_frames}
Mean frame RMS unit-vector error: {float(np.mean(frame_err)) if len(frame_err) else float('nan'):.8f}
Max frame RMS unit-vector error: {float(np.max(frame_err)) if len(frame_err) else float('nan'):.8f}
Raw candidate sites: {len(raw_sites_arr)}
Merged candidate sites: {len(merged_sites)}
Final BULK_TETRA sites: {len(final_sites)}

Outputs:
  {prefix}_sites.csv
  {prefix}_sites.xyz
  {prefix}_sites.lmp
  {prefix}_sites.npz
""".strip()
    Path(f"{prefix}_summary.txt").write_text(summary + "\n")
    print(summary)
    print(f"Wrote: {prefix}_sites.csv")
    print(f"Wrote: {prefix}_sites.xyz")
    print(f"Wrote: {prefix}_sites.lmp")
    print(f"Wrote: {prefix}_sites.npz")
    print(f"Wrote: {prefix}_summary.txt")


if __name__ == "__main__":
    main()
