#!/usr/bin/env bash
set -euo pipefail

# External-map Sigma5 Devanathan segment using ASE/LAMMPSlib NEB, bulk GCMC,
# rightward-only KMC hops, and the legacy one-crystal IR5/OR6 migration cache.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRACTICE_ROOT="${DEVANATHAN_PRACTICE_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"
cd "$PRACTICE_ROOT"

if [[ -d "$PRACTICE_ROOT/kmc_map_inputs" ]]; then
  MAP_ROOT="$PRACTICE_ROOT/kmc_map_inputs"
else
  MAP_ROOT="$(cd "$PRACTICE_ROOT/../.." && pwd)/kmc_map_inputs"
fi
if [[ ! -s "$MAP_ROOT/sigma5_stage3_unified_sites.npz" && -d "/scratch/rtirunelveli/LAMMPS/kmc_cluster_lammps_only/kmc_map_inputs" ]]; then
  MAP_ROOT="/scratch/rtirunelveli/LAMMPS/kmc_cluster_lammps_only/kmc_map_inputs"
fi

MAP_FILE="${KMC_SITE_MAP_FILE:-${MAP_ROOT}/sigma5_stage3_unified_sites.npz}"
HOST_FILE="${KMC_HOST_STRUCTURE_FILE:-${MAP_ROOT}/sigma5_210-20-20-5.lmp}"
REGION_FILE="${KMC_INITIAL_H_REGION_FILE:-${MAP_ROOT}/sigma5_site_regions.npz}"
POTENTIAL_FILE="${POTENTIAL_EAM_FILE:-${PRACTICE_ROOT}/kmc/PotentialB3410-modified.fs}"

LEGACY_SCHEMA="v4_envkey:mode:shell_IR5.0_OR6.0:env_plus_dir:R5.0_PB0.1_HB0.02:map:sigma5_stage3_unified_sites"
LEGACY_CACHE_DEFAULT="${PRACTICE_ROOT}/cache_bank/legacy_one_crystal_seed43_2m_ir5_or6.pkl"
LEGACY_CACHE="${LEGACY_CACHE:-${BARRIER_CACHE_FILE:-${LEGACY_CACHE_DEFAULT}}}"

for path in "$MAP_FILE" "$HOST_FILE" "$REGION_FILE" "$POTENTIAL_FILE" "$LEGACY_CACHE"; do
  if [[ ! -s "$path" ]]; then
    echo "Required input is missing or empty: $path" >&2
    exit 2
  fi
done

if [[ -z "${PYTHON_BIN:-}" ]]; then
  if [[ -x "/Users/rtirunelveli/kMC_code/python_kmc/bin/python" ]]; then
    export PYTHON_BIN="/Users/rtirunelveli/kMC_code/python_kmc/bin/python"
  elif command -v python >/dev/null 2>&1; then
    export PYTHON_BIN="$(command -v python)"
  elif command -v python3 >/dev/null 2>&1; then
    export PYTHON_BIN="$(command -v python3)"
  else
    echo "Could not find a Python interpreter. Set PYTHON_BIN." >&2
    exit 1
  fi
fi

export STEPS="${STEPS:-1000}"
export MPI_RANKS="${MPI_RANKS:-6}"
export RUN_ROOT="${RUN_ROOT:-runs/devanathan_external_gcmc_bulk_ase_legacy_$(date +%Y%m%d_%H%M%S)}"

export PYTHONPATH="${PRACTICE_ROOT}${PYTHONPATH:+:${PYTHONPATH}}"
export NEB_ENGINE=ase_lammps
export KMC_SITE_SOURCE=external
export KMC_SITE_MAP_FILE="$MAP_FILE"
export KMC_HOST_STRUCTURE_FILE="$HOST_FILE"
export KMC_HOST_FE_TYPE="${KMC_HOST_FE_TYPE:-1}"
export KMC_INITIAL_H_REGION_FILE="$REGION_FILE"

export NUM_H="${NUM_H:-50}"
export KMC_SEED="${KMC_SEED:-43}"
export DEVANATHAN_SEED="${DEVANATHAN_SEED:-43}"
export KNN_K="${KNN_K:-6}"

export LOCAL_ENV_MODE=shell
export ENV_KEY_MODE=env_plus_dir
export ENV_RADIUS_A=5.0
export POS_BIN_A=0.10
export HOP_BIN_A=0.02
export SHELL_INNER_RADIUS_A=5.0
export SHELL_OUTER_RADIUS_A=6.0

export POTENTIAL=EAM
export POTENTIAL_EAM_FILE="$POTENTIAL_FILE"
export LAMMPS_FILES="$POTENTIAL_FILE"

export NIMG="${NIMG:-3}"
export OPTIMIZE_ENDPOINTS="${OPTIMIZE_ENDPOINTS:-1}"
export NEB_OPTIMIZER_FMAX="${NEB_OPTIMIZER_FMAX:-0.05}"
export NEB_OPTIMIZER_STEPS="${NEB_OPTIMIZER_STEPS:-300}"
export ENDPOINT_OPTIMIZER_STEPS="${ENDPOINT_OPTIMIZER_STEPS:-200}"

export DEVANATHAN_ENABLED=1
export DEVANATHAN_SOURCE_MODE=gcmc_bulk
export DEVANATHAN_BULK_REGION="${DEVANATHAN_BULK_REGION:-bulk_grain_0}"
export DEVANATHAN_BULK_TARGET_N_H="${DEVANATHAN_BULK_TARGET_N_H:-50}"
export DEVANATHAN_BULK_TARGET_H_PER_FE="${DEVANATHAN_BULK_TARGET_H_PER_FE:-0.00311779011036977}"
export DEVANATHAN_BULK_X_MIN_A="${DEVANATHAN_BULK_X_MIN_A:-16.12518061159}"
export DEVANATHAN_SINK_X_MIN_A="${DEVANATHAN_SINK_X_MIN_A:-204.19906933748}"
export DEVANATHAN_BULK_SINK_GAP_A="${DEVANATHAN_BULK_SINK_GAP_A:-2.8601}"
export DEVANATHAN_BULK_X_MAX_A="${DEVANATHAN_BULK_X_MAX_A:-201.33896933748}"
export DEVANATHAN_SOURCE_X_MIN_A="${DEVANATHAN_BULK_X_MIN_A}"
export DEVANATHAN_SOURCE_X_MAX_A="${DEVANATHAN_BULK_X_MAX_A}"
export DEVANATHAN_SOURCE_LAYER_A="${DEVANATHAN_SOURCE_LAYER_A:-185.21378872589}"
export DEVANATHAN_SOURCE_FRACTION="${DEVANATHAN_SOURCE_FRACTION:-$DEVANATHAN_BULK_TARGET_H_PER_FE}"

export DEVANATHAN_LEFT_SINK_REGION="${DEVANATHAN_LEFT_SINK_REGION:-bulk_grain_0}"
export DEVANATHAN_LEFT_SINK_X_MIN_A="${DEVANATHAN_LEFT_SINK_X_MIN_A:-14.68828333}"
export DEVANATHAN_LEFT_SINK_X_MAX_A="${DEVANATHAN_LEFT_SINK_X_MAX_A:-16.12518061159}"
export KMC_HOP_X_DIRECTION="${KMC_HOP_X_DIRECTION:-right}"

export DEVANATHAN_GCMC_MU_EV="${DEVANATHAN_GCMC_MU_EV:--1.75}"
export DEVANATHAN_GCMC_TEMPERATURE_K="${DEVANATHAN_GCMC_TEMPERATURE_K:-300}"
export DEVANATHAN_GCMC_INITIALIZATION_START="${DEVANATHAN_GCMC_INITIALIZATION_START:-target}"
export DEVANATHAN_GCMC_MAINTENANCE_SETPOINT_MODE="${DEVANATHAN_GCMC_MAINTENANCE_SETPOINT_MODE:-target}"
export DEVANATHAN_GCMC_PRODUCTION_MODE="${DEVANATHAN_GCMC_PRODUCTION_MODE:-insert_delete}"
export DEVANATHAN_GCMC_ATTEMPTS_PER_ADJUSTMENT="${DEVANATHAN_GCMC_ATTEMPTS_PER_ADJUSTMENT:-8192}"
export DEVANATHAN_GCMC_INITIALIZATION_MIN_ATTEMPTS="${DEVANATHAN_GCMC_INITIALIZATION_MIN_ATTEMPTS:-2000}"
export DEVANATHAN_GCMC_INITIALIZATION_MAX_ATTEMPTS="${DEVANATHAN_GCMC_INITIALIZATION_MAX_ATTEMPTS:-10000}"
export DEVANATHAN_GCMC_CONVERGENCE_WINDOW="${DEVANATHAN_GCMC_CONVERGENCE_WINDOW:-1000}"
export DEVANATHAN_GCMC_CONVERGENCE_CHECK_INTERVAL="${DEVANATHAN_GCMC_CONVERGENCE_CHECK_INTERVAL:-250}"
export DEVANATHAN_GCMC_CONVERGENCE_DRIFT_H="${DEVANATHAN_GCMC_CONVERGENCE_DRIFT_H:-2.0}"
export DEVANATHAN_GCMC_TARGET_FRACTION_TOLERANCE="${DEVANATHAN_GCMC_TARGET_FRACTION_TOLERANCE:-0.0005}"
export DEVANATHAN_GCMC_CONVERGENCE_REQUIRED_CHECKS="${DEVANATHAN_GCMC_CONVERGENCE_REQUIRED_CHECKS:-1}"
export DEVANATHAN_GCMC_ACCEPT_NEAR_TARGET_AT_MAX="${DEVANATHAN_GCMC_ACCEPT_NEAR_TARGET_AT_MAX:-1}"
export DEVANATHAN_GCMC_PROGRESS_INTERVAL="${DEVANATHAN_GCMC_PROGRESS_INTERVAL:-250}"
export DEVANATHAN_GCMC_SHELL_INNER_RADIUS_A="${SHELL_INNER_RADIUS_A}"
export DEVANATHAN_GCMC_SHELL_OUTER_RADIUS_A="${SHELL_OUTER_RADIUS_A}"
export DEVANATHAN_GCMC_ENERGY_CACHE_ENABLED="${DEVANATHAN_GCMC_ENERGY_CACHE_ENABLED:-1}"
export DEVANATHAN_GCMC_ENERGY_CACHE_FILE="${DEVANATHAN_GCMC_ENERGY_CACHE_FILE:-$RUN_ROOT/cache/gcmc_bulk_energy_cache.pkl}"
export DEVANATHAN_GCMC_ENERGY_CACHE_POS_BIN_A="${DEVANATHAN_GCMC_ENERGY_CACHE_POS_BIN_A:-0.1}"
export DEVANATHAN_GCMC_ENERGY_CACHE_SAVE_INTERVAL="${DEVANATHAN_GCMC_ENERGY_CACHE_SAVE_INTERVAL:-100}"
export DEVANATHAN_GCMC_DIAG_PROPOSAL_LIMIT="${DEVANATHAN_GCMC_DIAG_PROPOSAL_LIMIT:-32}"

export KMC_INCREMENTAL_EVENTS="${KMC_INCREMENTAL_EVENTS:-1}"
export KMC_INCREMENTAL_IMPACT_RADIUS_A="${KMC_INCREMENTAL_IMPACT_RADIUS_A:-15.0}"
export CACHE_SCHEMA="${CACHE_SCHEMA:-$LEGACY_SCHEMA}"
export BARRIER_CACHE_FILE="$LEGACY_CACHE"
export JOB_ASSIGNMENT_MODE="${JOB_ASSIGNMENT_MODE:-cache_dedupe}"
export BARRIER_MERGE_MODE="${BARRIER_MERGE_MODE:-global}"
export BARRIER_MERGE_INTERVAL="${BARRIER_MERGE_INTERVAL:-100}"
export NEB_MIN_BATCH="${NEB_MIN_BATCH:-64}"

export RESTART_CHECKPOINT_INTERVAL="${RESTART_CHECKPOINT_INTERVAL:-1000}"
export DUMP_EVERY_STEPS="${DUMP_EVERY_STEPS:-1000}"
export DEBUG_MODE="${DEBUG_MODE:-0}"
export DEBUG_LOGGING="${DEBUG_LOGGING:-0}"
export WRITE_RATES_ALLRANKS="${WRITE_RATES_ALLRANKS:-0}"
export KMC_LOG_DIR="${KMC_LOG_DIR:-$RUN_ROOT/logs}"
export KMC_DIAGNOSTICS_DIR="${KMC_DIAGNOSTICS_DIR:-$RUN_ROOT/diagnostics}"
export KMC_TRAJECTORY_DIR="${KMC_TRAJECTORY_DIR:-$RUN_ROOT/trajectories}"
export KMC_CACHE_DIR="${KMC_CACHE_DIR:-$RUN_ROOT/cache}"
export KMC_NEB_DIR="${KMC_NEB_DIR:-$RUN_ROOT/neb}"
export RESTART_CHECKPOINT_DIR="${RESTART_CHECKPOINT_DIR:-$RUN_ROOT/checkpoints}"

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export VECLIB_MAXIMUM_THREADS="${VECLIB_MAXIMUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"

echo "Running external-map ASE GCMC-bulk Devanathan segment"
echo "  root=$PRACTICE_ROOT"
echo "  python=$PYTHON_BIN"
echo "  steps=$STEPS mpi_ranks=$MPI_RANKS"
echo "  map=$KMC_SITE_MAP_FILE"
echo "  host=$KMC_HOST_STRUCTURE_FILE"
echo "  bulk_region=$DEVANATHAN_BULK_REGION target_N_H=$DEVANATHAN_BULK_TARGET_N_H"
echo "  bulk_x=[${DEVANATHAN_BULK_X_MIN_A}, ${DEVANATHAN_BULK_X_MAX_A}) A"
echo "  left_sink=${DEVANATHAN_LEFT_SINK_REGION} x=[${DEVANATHAN_LEFT_SINK_X_MIN_A}, ${DEVANATHAN_LEFT_SINK_X_MAX_A}) A"
echo "  right_sink=x>=$DEVANATHAN_SINK_X_MIN_A A"
echo "  hop_x_direction=$KMC_HOP_X_DIRECTION"
echo "  cache_schema=$CACHE_SCHEMA"
echo "  barrier_cache=$BARRIER_CACHE_FILE"
echo "  output=$RUN_ROOT"

if [[ "${DRY_RUN:-0}" == "1" ]]; then
  exit 0
fi

if [[ "$MPI_RANKS" == "1" ]]; then
  "$PYTHON_BIN" -m kmc.main
else
  mpirun -np "$MPI_RANKS" "$PYTHON_BIN" -m kmc.main
fi
